### ISSUE TITLE
Incompatibility with formatnumber

### ISSUE THREAD

**Issue by ziggi** [Y-Less/sscanf#15]
`formatnumber` cause an error `sources\lib/formatnumber.inc(115) : error 020: invalid symbol name ""` related with [this string](https://github.com/Open-GTO/Open-GTO/blob/master/sources/lib/formatnumber.inc#L115):
```Pawn
else if ( iTag == tagof( hex: ) || iTag == tagof( Hex: ) )
```
But I use some other version of sscanf2.inc where this bug [is fixed](https://github.com/Open-GTO/Open-GTO/blob/master/sources/lib/sscanf2.inc#L321):
```Pawn
#define hex:%0;unformat(_:EXTRZ:EXTRX:%1); %0;unformat(_:EXTRZ:EXTRX:%1); 
```
And I'm pretty sure what this changes was made not by me.
So, I we can made this changes without any fears of incompatibility or not?

**Comment by maddinat0r** [comment]
I had to slightly change that fix, as it only worked with certain invocations of the extract macro. It also shouldn't break compatibility.

Also that formatnumber include seems to crash the default PAWN compiler, had to test it with Zeex' compiler fork.

**Comment by Y-Less** [comment]
Should probably do the same for the other bare tags, since they might not be used elsewhere right now, but that doesn't mean they can't be.
