### ISSUE TITLE
extract macro in 3.10.5 broken by new feature

### ISSUE THREAD

**Issue by Y-Less** [Y-Less/sscanf#16]
https://github.com/Zeex/pawn/issues/224

This is not a bug in sscanf, but probably fastest to fix here. Looking thorough the code I don't actually see a reason why a double hash is needed at all - a single should do.

**Comment by maddinat0r** [comment]
Simply replacing `##` with `#` did fix this, thanks!

**Comment by Y-Less** [comment]
Just noting @m1n1vv first reported this.  Thanks.
