### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ghost** [Y-Less/sscanf#20]
```
new 
text[85], action[85]; 
if (sscanf(params, "p<*>s[85]s[85]", text, action)) { 
    SendClientMessage(playerid, -1, "- /todo [text*action]"); 
    return 1; 
}  

```
/ todo *test, that is, the first (text) can be skipped

I fixed it
`if (sscanf(params, "p<*>s[85]s[85]", text, action) || params[strfind(params, "*", true) - 1] == '\0')  `

**Comment by ur-Krass** [comment]
> ```
> new 
> text[85], action[85]; 
> if (sscanf(params, "p<*>s[85]s[85]", text, action)) { 
>     SendClientMessage(playerid, COLOR_GRAY, "- /todo [text*action]"); 
>     return 1; 
> }  
> ```
> / todo *test, that is, the first (text) can be skipped
> 
> I fixed it
> `if (sscanf(params, "p<*>s[85]s[85]", text, action) || params[strfind(params, "*", true) - 1] == '\0')`

**Comment by ur-Krass** [comment]
> ```
> new 
> text[85], action[85]; 
> if (sscanf(params, "p<*>s[85]s[85]", text, action)) { 
>     SendClientMessage(playerid, -1, "- /todo [text*action]"); 
>     return 1; 
> }  
> ```
> / todo *test, that is, the first (text) can be skipped
> 
> I fixed it
> `if (sscanf(params, "p<*>s[85]s[85]", text, action) || params[strfind(params, "*", true) - 1] == '\0')`

**Comment by maddinat0r** [comment]
Judging by the plugin code, this does not look like a bug. The plugin simply parses an empty string into `text`. You should just check if `text` is empty, i.e. `text[0] == '\0'`.

**Comment by ghost** [comment]
But, at me, for some reason it didn't turn out with `text[0]`
Works if I make `text[-1]`

Using Pawn.CMD

**Comment by maddinat0r** [comment]
`text[-1]` isn't valid PAWN code and won't compile.
So yeah, this isn't a plugin bug.
