### ISSUE TITLE
extract macro can't handle Float tag

### ISSUE THREAD

**Issue by Daniel-Cortez** [Y-Less/sscanf#23]
`extract` macro gives an error in the following example:
```Pawn
#include <a_samp>
#include <sscanf2>
main()
{
	static params[] = "4 5.0";
	extract params -> new vehicleid, Float:fuel; // error 029: invalid expression, assumed zero
}
```
It seems that the problem was introduced in 9d54c11d3320a5bccf20ce880b1a9ed9514920ca, the above example compiles well with the previous versions of sscanf2.inc.

**Comment by Y-Less** [comment]
Fixed.
