### ISSUE TITLE
bug player name "u" and "r"

### ISSUE THREAD

**Issue by ykosovskyi** [Y-Less/sscanf#25]
Online 2 players:
[ID: 1] Mark_Dwellers 
[ID: 2] Mark_Dwellerss 

**// Test 1: correct**
sscanf("Mark_Dwellers", "u", id); 
// result: id = 1;

**// Test 2: error**
sscanf("Mark_Dwellerss", "u", id); 
// result: id = 1; should be: id = 2;

**Comment by Crayder** [comment]
It's the first full-match... @maddinat0r you should implement a Levenshtein distance algorithm for matching play names. That would be a great way around this. The same would be great for k<vehicle>.

**Comment by Crayder** [comment]
Temporarily, I decided to provide @ykosovskyi a solution.

```pawn
mathMin(inp1,inp2)
	return (inp1 > inp2 ? inp2 : inp1);

LevenshteinDistance(strs[], strt[])
{
	new n = strlen(strs), m = strlen(strt);
	
	new d[128][128];

	if (n == 0)
		return m;

	if (m == 0)
		return n;

	for (new i; i <= n; i++)
		d[i][0] = i;
	
	for (new j; j <= m; j++)
		d[0][j] = j;

	for (new j = 1; j <= m; j++)
	{
		for (new i = 1; i <= n; i++)
		{
			if (strs[i - 1] == strt[j - 1])
				d[i][j] = d[i - 1][j - 1];
			else
				d[i][j] = mathMin(mathMin(d[i - 1][j] + 1, d[i][j - 1] + 1), d[i - 1][j - 1] + 1);
		}
	}
	return d[n][m];
}

SSCANF:pname(string[])
{
	new Iterator:selected<MAX_PLAYERS>;
	new distance[MAX_PLAYERS], least = MAX_PLAYER_NAME;
	
	foreach(new i: Player)
	{
		new name[MAX_PLAYER_NAME];
		GetPlayerName(i, name, sizeof(name));
		
		if(strfind(name, string, true) != -1)
		{
			distance = LevenshteinDistance(string, name);
			
			if(least > distance)
			{
				Iter_Add(selected, i);
				least = distance;
			}
		}
	}
	
	return Iter_Last(selected);
}
```

As I suggested previously, this uses Levenshtein distance to calculate which player's name matches best. This example uses y_iterate, which vastly simplifies this entire snippet and makes it run pretty darn fast.



In case you don't know how to use "kustom" sscanf params, simply change `u` to `k<pname>`.

**Comment by ykosovskyi** [comment]
Thank, @Crayder . I did that. While in the sscanf will not be fixed.

```pawn
new Array_GetPlayerID[MAX_PLAYERS];
stock GetPlayerIDFromName(name[])
{
	new need_len = strlen(name);
	new count = 0;
	forPlayers(i)
	{
		if(strlen(PN(i)) == need_len) Array_GetPlayerID[count++] = i;
	}
	for(new i = 0; i < count; i++)
	{
		if(!strcmp(name, PN(Array_GetPlayerID[i]), false))
		{
			return Array_GetPlayerID[i];
		}
	}
	return INVALID_PLAYER_ID;
}
```

**Comment by Crayder** [comment]
It's not something that needs "fixed" in my opinion, it works as it should. It returns the first full matching player name. That's why I suggested the distance function separately.

**Comment by ykosovskyi** [comment]
It would be nice to fix this way:
In the specifier "u" add a check for the length of the input nickname and the one that found, if not the same - continue the search.

**Comment by Crayder** [comment]
The input can be any length however, so that will not help

**Comment by Y-Less** [comment]
Check the `MATCH_NAME_PARTIAL` and `CELLMIN_ON_MATCHES` options.
