### ISSUE TITLE
I can't use sscanf with only strings?

### ISSUE THREAD

**Issue by Walter-Correa** [Y-Less/sscanf#28]
https://forum.sa-mp.com/showthread.php?t=676737

**Comment by Y-Less** [comment]
Can you repost this issue please?  Obviously the SA:MP forums are gone now so I can't see that.

**Comment by Walter-Correa** [comment]
> Can you repost this issue please? Obviously the SA:MP forums are gone now so I can't see that.

Hello!
I posted here too: https://www.burgershot.gg/showthread.php?tid=426&pid=11740#pid11740

**Comment by Walter-Correa** [comment]
@Y-Less https://forum.open.mp/showthread.php?tid=426&pid=11740#pid11740
