### ISSUE TITLE
Variable overflow

### ISSUE THREAD

**Issue by tr1xy** [Y-Less/sscanf#29]
I am opening issue here as I cannot contact @Y-Less elsewhere

Is it possible to evade variable overflows on positive values?
Because if **i** specifier is higher than cellmax, it'll obviously go below zero and possibly to cellmin and back, I can prevent negative values in my functions easily but this'd be cool enhancement (if it is doable) 👍

**Comment by tr1xy** [comment]
Actually, I did more testing and this can be consideres as an the bug because
`/givemoney 0 20000000000000000000000000000`
`20000000000000000000000000000` becomes `536870912 `

**Comment by Y-Less** [comment]
No, that's not possible.  Numbers are limited to the 32bit cell limit.
