### ISSUE TITLE
Version mess

### ISSUE THREAD

**Issue by NexiusTailer** [Y-Less/sscanf#38]
There are currently some positioning issues with newer versions of the plugin which are released in a fork of this repository as part of the newer 2.10 branch: https://github.com/Y-Less/sscanf

Perhaps it would be more wise to combine these 2 repos into one (for example, this one, since it has been around for years), separating new releases into a new git branch and making it the main one?

I am also interested in the relevance of [this branch](https://github.com/Y-Less/sscanf-3.0) of releases in relation to 2.8.* and 2.10.* versions.

**Comment by NexiusTailer** [comment]
Sorry if I'm not creating this inside a fork repos where this issue would be more appropriate, but it seems that this section is disabled there, so this is here.

**Comment by Y-Less** [comment]
The forks are resolved now.

**Comment by NexiusTailer** [comment]
Nice to see. Could be another merge of [sscanf-3.0 repo](https://github.com/Y-Less/sscanf-3.0) into this branch in here:
![image](https://user-images.githubusercontent.com/13169094/160504771-76ed83ce-1d56-4e90-ada5-35e3edc7f5cb.png)
(which is already exist anyway)

Obv 3.0 (both the separate repo and a branch here) is abandoned, but having one united repo with a couple branches for one project should be the best option if someone will look for other version branches I suppose.
