### ISSUE TITLE
More warnings

### ISSUE THREAD

**Issue by NoPressF** [Y-Less/sscanf#45]
Hello, after updating sscanf2 to the latest version, by connecting sscanf2 include, there are 26 errors after compilation, and more than 20+ warnings.
`
// These are connected includes.
#include                                 <a_samp>
#include                                 <a_http>
#include                                 <a_mysql>
#include                                 <crashdetect>
#include                                 <mdialog>
#include                                 <callbacks>
#include                                 <sscanf2>
#include                                 <streamer>
#include                                 <colandreas>
#include                                 <foreach>
#include                                 <YSF>
#include                                 <nex-ac>
#include                                 <PlayerNearDetailCar>
#include                                 <audio>
#include                                 <progress_bar>
#include                                 <Pawn.CMD>
#include                                 <geolocation>
#include                                 <objectweaponsutil>
`
`C:\Users\Vova\Desktop\Zombie Project\pawno\include\mdialog.inc(656) : warning 219: local variable "i" shadows a variable at a preceding level
C:\Users\Vova\Desktop\Zombie Project\pawno\include\mdialog.inc(706) : warning 219: local variable "i" shadows a variable at a preceding level
C:\Users\Vova\Desktop\Zombie Project\pawno\include\callbacks.inc(363) : warning 219: local variable "i" shadows a variable at a preceding level
C:\Users\Vova\Desktop\Zombie Project\pawno\include\callbacks.inc(516) : warning 219: local variable "i" shadows a variable at a preceding level
C:\Users\Vova\Desktop\Zombie Project\pawno\include\callbacks.inc(651) : warning 219: local variable "i" shadows a variable at a preceding level
C:\Users\Vova\Desktop\Zombie Project\pawno\include\callbacks.inc(669) : warning 219: local variable "i" shadows a variable at a preceding level
C:\Users\Vova\Desktop\Zombie Project\pawno\include\callbacks.inc(812) : warning 219: local variable "i" shadows a variable at a preceding level
C:\Users\Vova\Desktop\Zombie Project\pawno\include\callbacks.inc(940) : warning 219: local variable "i" shadows a variable at a preceding level
C:\Users\Vova\Desktop\Zombie Project\pawno\include\callbacks.inc(1153) : warning 219: local variable "i" shadows a variable at a preceding level
C:\Users\Vova\Desktop\Zombie Project\pawno\include\sscanf2.inc(394) : warning 219: local variable "name" shadows a variable at a preceding level
C:\Users\Vova\Desktop\Zombie Project\pawno\include\sscanf2.inc(812) : warning 219: local variable "name" shadows a variable at a preceding level
C:\Users\Vova\Desktop\Zombie Project\pawno\include\sscanf2.inc(818) : warning 219: local variable "i" shadows a variable at a preceding level
C:\Users\Vova\Desktop\Zombie Project\pawno\include\sscanf2.inc(1031) : warning 219: local variable "name" shadows a variable at a preceding level
C:\Users\Vova\Desktop\Zombie Project\pawno\include\colandreas.inc(721) : warning 219: local variable "i" shadows a variable at a preceding level
C:\Users\Vova\Desktop\Zombie Project\pawno\include\colandreas.inc(915) : warning 219: local variable "i" shadows a variable at a preceding level
C:\Users\Vova\Desktop\Zombie Project\pawno\include\foreach.inc(1582) : warning 219: local variable "i" shadows a variable at a preceding level
C:\Users\Vova\Desktop\Zombie Project\pawno\include\foreach.inc(1607) : warning 219: local variable "i" shadows a variable at a preceding level
C:\Users\Vova\Desktop\Zombie Project\pawno\include\PlayerNearDetailCar.inc(191) : warning 219: local variable "id" shadows a variable at a preceding level
C:\Users\Vova\Desktop\Zombie Project\pawno\include\audio.inc(137) : warning 219: local variable "name" shadows a variable at a preceding level
C:\Users\Vova\Desktop\Zombie Project\pawno\include\audio.inc(182) : warning 219: local variable "name" shadows a variable at a preceding level
C:\Users\Vova\Desktop\Zombie Project\pawno\include\progress_bar.inc(141) : warning 219: local variable "i" shadows a variable at a preceding level
C:\Users\Vova\Desktop\Zombie Project\pawno\include\geolocation.inc(76) : error 017: undefined symbol "sscanf_"; did you mean "SSCANF__"?
C:\Users\Vova\Desktop\Zombie Project\pawno\include\geolocation.inc(287) : error 017: undefined symbol "sscanf_"; did you mean "SSCANF__"?
C:\Users\Vova\Desktop\Zombie Project\pawno\include\geolocation.inc(305) : error 001: expected token: ";", but found "{"
C:\Users\Vova\Desktop\Zombie Project\pawno\include\geolocation.inc(307) : error 010: invalid function or declaration
C:\Users\Vova\Desktop\Zombie Project\pawno\include\geolocation.inc(311) : error 055: start of function body without function header
C:\Users\Vova\Desktop\Zombie Project\pawno\include\geolocation.inc(312) : error 010: invalid function or declaration
C:\Users\Vova\Desktop\Zombie Project\pawno\include\geolocation.inc(319) : error 001: expected token: ";", but found ")"
C:\Users\Vova\Desktop\Zombie Project\pawno\include\geolocation.inc(321) : error 010: invalid function or declaration
C:\Users\Vova\Desktop\Zombie Project\pawno\include\geolocation.inc(325) : error 010: invalid function or declaration
C:\Users\Vova\Desktop\Zombie Project\pawno\include\geolocation.inc(327) : error 010: invalid function or declaration
C:\Users\Vova\Desktop\Zombie Project\pawno\include\geolocation.inc(329) : error 010: invalid function or declaration
C:\Users\Vova\Desktop\Zombie Project\pawno\include\geolocation.inc(331) : error 010: invalid function or declaration
C:\Users\Vova\Desktop\Zombie Project\pawno\include\geolocation.inc(333) : error 010: invalid function or declaration
C:\Users\Vova\Desktop\Zombie Project\pawno\include\geolocation.inc(338) : error 001: expected token: ";", but found "-identifier-"
C:\Users\Vova\Desktop\Zombie Project\pawno\include\geolocation.inc(339) : error 010: invalid function or declaration
C:\Users\Vova\Desktop\Zombie Project\pawno\include\geolocation.inc(344) : error 010: invalid function or declaration
C:\Users\Vova\Desktop\Zombie Project\pawno\include\geolocation.inc(347) : error 010: invalid function or declaration
C:\Users\Vova\Desktop\Zombie Project\pawno\include\geolocation.inc(351) : error 010: invalid function or declaration
C:\Users\Vova\Desktop\Zombie Project\pawno\include\geolocation.inc(353) : error 010: invalid function or declaration
C:\Users\Vova\Desktop\Zombie Project\pawno\include\geolocation.inc(356) : error 010: invalid function or declaration
C:\Users\Vova\Desktop\Zombie Project\pawno\include\geolocation.inc(359) : error 010: invalid function or declaration
C:\Users\Vova\Desktop\Zombie Project\pawno\include\geolocation.inc(362) : error 021: symbol already defined: "num"
C:\Users\Vova\Desktop\Zombie Project\pawno\include\geolocation.inc(364) : error 010: invalid function or declaration
C:\Users\Vova\Desktop\Zombie Project\pawno\include\geolocation.inc(367) : error 010: invalid function or declaration
C:\Users\Vova\Desktop\Zombie Project\pawno\include\geolocation.inc(369) : error 010: invalid function or declaration
C:\Users\Vova\Desktop\Zombie Project\pawno\include\geolocation.inc(372) : error 010: invalid function or declaration

Compilation aborted.

Pawn compiler 3.10.10	 	 	Copyright (c) 1997-2006, ITB CompuPhase

26 Errors.
`
How to fix it?

**Comment by Y-Less** [comment]
You're missing a brace somewhere.  It sin't in sscanf2.inc.
