### ISSUE TITLE
Run time error 19: "File or function is not found"

### ISSUE THREAD

**Issue by marioamriansyah** [Y-Less/sscanf#46]
![image](https://user-images.githubusercontent.com/49476946/170874095-8a9922b9-42e6-4f40-9f0c-f8d944cbe415.png)

**Comment by marioamriansyah** [comment]
If used #include <sscanf2> occur Error on samp-server.exe
and if you remove #include #include <sscanf2> samp-server.exe normal Running

**Comment by Y-Less** [comment]
try the latest version.
