### ISSUE TITLE
new version - shit

### ISSUE THREAD

**Issue by plakapenka** [Y-Less/sscanf#51]
[2022-12-27T02:05:37+0300] [Info] Loading plugin: sscanf
[2022-12-27T02:05:37+0300] [Info] Could not load plugin:

omp 11

**Comment by iamkovshevoy** [comment]
[Info] Could not load plugin:
/lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/7480/18727/plugins/sscanf.so)

Maybe my hosting have problem with this, but, I have problem with plugin too.

**Comment by Y-Less** [comment]
Yeah, that's known when people are on old versions of glibc.  I've got a system set up to build using docker now, it'll be fixed today.

**Comment by Y-Less** [comment]
The problem is that my Linux server is up-to-date, so when I build on that system people on older systems can't use the binary.

**Comment by Y-Less** [comment]
https://github.com/Y-Less/sscanf/releases/tag/v.2.13.5

Try this version.  I've fixed some bugs and build on older glibc (I hope).
