### ISSUE TITLE
SetPlayerName problems with sscanf 2.13.8

### ISSUE THREAD

**Issue by Tiaansu** [Y-Less/sscanf#59]
**sscanf version**: 2.13.8
**server**: open.mp RC2

When I set the player's name then use sscanf, the `u` specifier doesn't detect the new name and only detects the player's old name.

Code:
```pawn
#include <open.mp>
#include <sscanf2>

main(){}

public OnGameModeInit()
{
    AddPlayerClass(0, 1958.3783, 1343.1572, 15.3746, 269.1425, WEAPON_FIST, 0, WEAPON_FIST, 0, WEAPON_FIST, 0);
    return 1;
}

public OnPlayerRequestClass(playerid, classid)
{
	SetPlayerPos(playerid, 1958.3783, 1343.1572, 15.3746);
	SetPlayerCameraPos(playerid, 1958.3783, 1343.1572, 15.3746);
	SetPlayerCameraLookAt(playerid, 1958.3783, 1343.1572, 15.3746);
	return 1;
}

public OnPlayerSpawn(playerid)
{
    SetPlayerName(playerid, "Test_Account");
}

public OnPlayerText(playerid, text[])
{
    new targetid;

    sscanf(text, "u", targetid);

    if (!IsPlayerConnected(targetid))
    {
        SendClientMessage(playerid, -1, "Player with name %s is disconnected", text);
    }
    else
    {
        SendClientMessage(playerid, -1, "Player with name %s is connected", text);
    }
}
```

**Comment by Y-Less** [comment]
Are you using it as a plugin or a component?

**Comment by DitzySeruni** [comment]
> Are you using it as a plugin or a component?

Yeah it's work when i switch to component, ty.

**Comment by Tiaansu** [comment]
> Are you using it as a plugin or a component?

Hello, sorry for the late reply, I'm using it as a plugin. Will try to use it as component when I go back at coding with pawn again. Thank you.

**Comment by Tiaansu** [comment]
> Are you using it as a plugin or a component?

Hello, just got back at coding with pawn, it works when I'm using it as component and not if I'm using it in plugin. Will close the issue now, thank you.
